services:
  db-local:
    image: postgres:16-alpine
    container_name: ai-chat-database
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=chatAdmin
      - POSTGRES_DB=ai_chat
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5434:5432"
    volumes:
      - ./data/database-local:/var/lib/postgresql/data
    networks:
      - ai-chat-network

volumes:
  postgres_data:


