version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: ai-chat-database
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=chatAdmin
      - POSTGRES_DB=ai_chat
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5435:5432"
    volumes:
      - ./data/database-chat-local:/var/lib/postgresql/data

volumes:
  postgres_data:



